/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3;

public class Library {
	public static void main(String arg[]) {
		comp3111.lab3.ex2.UIApplication.run(arg);
	}
}
